### ISSUE TITLE
Does not work on macOS

### ISSUE THREAD

**Issue by seitbekir-seidametov-codeit** [ivangsa/vs-asyncapi-preview#1]
Today I found this extension and that was inspiring due to exceptions, I already using Swagger Viewer. But unfortunately it works only on linux, which would be fine, but I use macOS mainly. The only thing I see when I open a viewer is black message:

```
Cannot GET /file//Users/.../asyncapi.yml
```

I've tried to play around, but did not find quick solution.

**Comment by ivangsa** [comment]
Hi @seitbekir-seidametov-codeit 
I don't have a macOS to test... 

Maybe you can help me track this..

Can you try setting this config `asyncapiPreview.previewInBrowser` to true, so you can open preview in chrome
Inside chrome devtools console try this javascript `window.location.pathname.replace(/\/file\//g, '');`

I'm guessing that in macOS is not doing the replacement of /file/ prefix

Thanks and sorry for the delay answering

**Comment by nealdam** [comment]
Using Arch Linux, it's also not doing the replacement of /file/ prefix
`Cannot GET /file//home/.../tabata.yaml`

**Comment by ivangsa** [comment]
Hi @nealdam and @seitbekir-seidametov-codeit  

I have uploaded version 0.0.3 to the marketplace which fixes this issue

Sorry for the delay fixing this
